# Generated by Django 5.2.6 on 2025-09-07 17:00

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to=books.models.book_cover_upload_path),
        ),
    ]
