# Generated by Django 5.2.6 on 2025-09-07 17:10

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, help_text='Загрузите файл книги (PDF, EPUB, DOC, DOCX)', null=True, upload_to=books.models.book_file_upload_path),
        ),
    ]
