# Generated by Django 5.2.6 on 2025-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_goodreads_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='add_photo_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='add_video_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='goodreads_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='print_book_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='print_book_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reading_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('kindle_unlimited', 'Kindle Unlimited'), ('verified_ebook', 'Verified Purchase (eBook)'), ('verified_print', 'Verified Print Copy')], max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stars_cost',
            field=models.IntegerField(default=0, help_text='Количество звезд, необходимых для получения обзоров'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('live', 'Live'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
    ]
