# Generated by Django 5.2.6 on 2025-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_add_goodreads_review_book_add_photo_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preferred_marketplace',
            field=models.CharField(blank=True, choices=[('CA', 'Amazon Canada'), ('FR', 'France'), ('DE', 'Germany'), ('US', 'USA'), ('GB', 'UK'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('JP', 'Japan'), ('MX', 'Mexico'), ('BR', 'Brazil'), ('ID', 'Indonesia'), ('PL', 'Poland'), ('AU', 'Australia')], help_text='Предпочтительный маркетплейс для получения отзывов', max_length=2),
        ),
    ]
