# Generated by Django 5.2.6 on 2025-09-07 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_preferred_marketplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('reading', 'Reading'), ('review_submitted', 'Review Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('link_pending', 'Link Pending')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_reading_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_link', models.URLField(blank=True)),
                ('stars_reward', models.IntegerField(default=100)),
                ('pages_read', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'reader')},
            },
        ),
    ]
