# Generated by Django 5.2.6 on 2025-09-11 14:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookassignment',
            name='pages_read',
        ),
        migrations.RemoveField(
            model_name='bookassignment',
            name='total_pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=models.CharField(blank=True, help_text='You can find in book description', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text="Enter author's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, help_text='Upload book file (PDF, EPUB, DOC, DOCX)', null=True, upload_to=books.models.book_file_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload book cover', null=True, upload_to=books.models.book_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('coloring_books', 'Coloring Books | Low Content'), ('journals', 'Journals | Low Content'), ('planners', 'Planners | Low Content'), ('recipe_books', 'Recipe Books | Low Content'), ('quote_books', 'Quote Books | Low Content'), ('activity_books', 'Activity Books | Low Content'), ('trivia_books', 'Trivia Books | Low Content'), ('sudoku', 'Sudoku | Low Content'), ('crosswords', 'Crosswords | Low Content'), ('word_search', 'Word Search | Low Content'), ('childrens_book', "Children's Book | Low Content"), ('other_low_content', 'Other Low Content / No Content'), ('religion_and_spirituality', 'Religion and Spirituality | Non-fiction'), ('health_fitness_dieting', 'Health, Fitness and Dieting | Non-fiction'), ('politics_social_sciences', 'Politics and Social Sciences | Non-fiction'), ('cook_books_food_wine', 'Cook Books, Food and Wine | Non-fiction'), ('business_money', 'Business and Money | Non-fiction'), ('parenting_relationship', 'Parenting and Relationship | Non-fiction'), ('self_help', 'Self Help | Non-fiction'), ('biography_memories', 'Biography and Memories | Non-fiction'), ('education_teaching', 'Education and Teaching | Non-fiction'), ('crafts_hobbies_home', 'Crafts, Hobbies and Home | Non-fiction'), ('other_non_fiction', 'Other Non-fiction'), ('fiction', 'Fiction'), ('romance', 'Romance | Fiction'), ('sci-fi', 'Sci-Fi | Fiction'), ('non_english', 'Non-English')], default='other_low_content', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Deutsch', 'Deutsch'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish'), ('Other', 'Other')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='preferred_marketplace',
            field=models.CharField(choices=[('CA', 'Amazon Canada'), ('FR', 'France'), ('DE', 'Germany'), ('US', 'USA'), ('GB', 'UK'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('JP', 'Japan'), ('MX', 'Mexico'), ('BR', 'Brazil'), ('ID', 'Indonesia'), ('PL', 'Poland'), ('AU', 'Australia')], help_text='Preferred marketplace for reviews', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars_cost',
            field=models.IntegerField(default=0, help_text='Number of stars required to get reviews'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Enter full book name including subtitle', max_length=255),
        ),
    ]
