# Generated by Django 5.2.6 on 2025-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_bookassignment_pages_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_info',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('live', 'Live'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('live', 'Live'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='word_count',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('live', 'Live'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], max_length=255, null=True),
        ),
    ]
