# Generated by Django 5.2.6 on 2025-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starbalance',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starbalance',
            name='total_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starbalance',
            name='total_spent',
            field=models.IntegerField(default=0),
        ),
    ]
